const store={get:(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},set:(key,value)=>localStorage.setItem(key,JSON.stringify(value))};
const DAYS=['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'];
const MEALS=[['breakfast','Ontbijt'],['snack1','Snack 1'],['lunch','Lunch'],['snack2','Snack 2'],['dinner','Avondeten'],['snack3','Snack 3']];
const BASE_SCHEDULE=DAYS.map(day=>({day,type:'Rust',title:'Nog niet ingevuld',note:''}));
const DEFAULT_PLAN={id:'plan-template',title:'Nieuw trainingsschema',description:'Persoonlijk schema.',sessions:[{day:'Maandag',title:'Training 1',exercises:[{name:'Nieuwe oefening',sets:3,reps:'10',method:'normal'}]}]};
let state={view:store.get('coachView','clients'),clients:store.get('coachClients',[]),clientId:store.get('coachClientId',''),nutrition:store.get('coachNutritionPlans',{}),schedules:store.get('coachSchedules',{}),goals:store.get('coachGoals',{}),plans:store.get('trainingPlans',[structuredClone(DEFAULT_PLAN)]),assignments:store.get('clientPlanAssignments',{}),editingPlanId:store.get('coachEditingPlanId','plan-template')};
if(!state.clients.some(x=>x.id===state.clientId))state.clientId=state.clients[0]?.id||'';
const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function persist(){store.set('coachClients',state.clients);store.set('coachClientId',state.clientId);store.set('coachNutritionPlans',state.nutrition);store.set('coachSchedules',state.schedules);store.set('coachGoals',state.goals);store.set('trainingPlans',state.plans);store.set('clientPlanAssignments',state.assignments);store.set('coachEditingPlanId',state.editingPlanId);window.KaradaCoachCloud?.scheduleSync(structuredClone({clients:state.clients,nutrition:state.nutrition,schedules:state.schedules,goals:state.goals,plans:state.plans,assignments:state.assignments}))}
function client(id=state.clientId){return state.clients.find(x=>x.id===id)||null}
function noClient(){return `<section class="empty-state"><span>＋</span><h2>Maak eerst een klant aan</h2><p>Een klant krijgt pas toegang nadat naam en e-mailadres hier zijn toegevoegd.</p><button onclick="openClients()">Klant toevoegen</button></section>`}
function openClients(){state.view='clients';store.set('coachView',state.view);render()}
function renderClients(){return `<div class="intro"><div><span class="label">Toegang en koppeling</span><h2>Klanten</h2><p>Alleen e-mailadressen uit deze lijst kunnen straks in de klantenapp worden gekoppeld.</p></div><span class="pill">${state.clients.length} klanten</span></div><section class="card"><h3>Nieuwe klant</h3><div class="client-form"><label>Naam<input id="newClientName" autocomplete="name" placeholder="Voor- en achternaam"></label><label>E-mailadres<input id="newClientEmail" type="email" autocomplete="email" placeholder="naam@voorbeeld.nl"></label><label>Doel<input id="newClientGoal" placeholder="Bijv. sterker worden"></label><button onclick="addClient()">Klant toevoegen</button></div></section><section class="card"><h3>Actieve klanten</h3><div class="client-list">${state.clients.map(c=>`<article><div><b>${esc(c.name)}</b><span>${esc(c.email)}</span><small>${esc(c.goal||'Nog geen doel')}</small></div><div><button class="subtle" onclick="selectClient('${c.id}')">Open klant</button><button class="danger" onclick="removeClient('${c.id}')">Verwijder</button></div></article>`).join('')||'<p class="empty">Nog geen klanten. Voeg hierboven de eerste klant toe.</p>'}</div></section>`}
function addClient(){const name=$('#newClientName')?.value.trim(),email=$('#newClientEmail')?.value.trim().toLowerCase(),goal=$('#newClientGoal')?.value.trim();if(!name||!/^\S+@\S+\.\S+$/.test(email))return toast('Vul een naam en geldig e-mailadres in');if(state.clients.some(x=>x.email===email))return toast('Dit e-mailadres bestaat al');const id=`client-${crypto.randomUUID?.()||Date.now()}`;state.clients.push({id,name,email,goal,active:true,createdAt:new Date().toISOString()});state.clientId=id;persist();syncClientSelect();render();toast(`${name} is als klant toegevoegd`)}
function removeClient(id){const c=client(id);if(!c||!confirm(`Klant ${c.name} verwijderen?`))return;state.clients=state.clients.filter(x=>x.id!==id);delete state.nutrition[id];delete state.schedules[id];delete state.goals[id];delete state.assignments[id];if(state.clientId===id)state.clientId=state.clients[0]?.id||'';persist();syncClientSelect();render();toast('Klant verwijderd')}
function selectClient(id){state.clientId=id;state.view='nutrition';persist();syncClientSelect();render()}
function nutritionPlan(){return state.nutrition[state.clientId]||{carbs:300,protein:150,fat:80,note:'Verdeel je voeding over zes eetmomenten.',meals:{}}}
function renderNutrition(){if(!client())return noClient();const p=nutritionPlan(),kcal=p.carbs*4+p.protein*4+p.fat*9;return `<div class="intro"><div><span class="label">Voedingscoaching</span><h2>Voedingsplan voor ${esc(client().name)}</h2><p>Stel de dagelijkse macro’s en instructies per eetmoment in. De klant registreert alleen wat er is gegeten.</p></div><span class="pill">Coach bepaalt</span></div><section class="card"><span class="label">Dagdoel</span><h3>Macro’s per dag</h3><div class="macro-grid"><div class="field"><label>Koolhydraten (g)</label><input id="carbs" type="number" min="0" value="${p.carbs}" oninput="updateKcal()"><small>4 kcal per gram</small></div><div class="field"><label>Eiwit (g)</label><input id="protein" type="number" min="0" value="${p.protein}" oninput="updateKcal()"><small>4 kcal per gram</small></div><div class="field"><label>Vet (g)</label><input id="fat" type="number" min="0" value="${p.fat}" oninput="updateKcal()"><small>9 kcal per gram</small></div><div class="kcal-preview" id="kcal">${kcal.toLocaleString('nl-NL')} kcal</div></div><div class="field note-field"><label>Algemene instructie voor de klant</label><textarea id="note" rows="3">${esc(p.note||'')}</textarea></div></section><section class="card"><span class="label">Zes eetmomenten</span><h3>Richtlijn per maaltijd</h3><div class="meal-guidance">${MEALS.map(([id,label])=>`<div><label>${label}</label><input id="meal-${id}" value="${esc(p.meals?.[id]||'')}" placeholder="Bijv. eiwitrijk en 60 g koolhydraten"></div>`).join('')}</div><div class="actions"><button onclick="saveNutrition()">Voedingsplan opslaan</button></div></section>`}
function updateKcal(){const c=+$('#carbs').value||0,p=+$('#protein').value||0,f=+$('#fat').value||0;$('#kcal').textContent=`${Math.round(c*4+p*4+f*9).toLocaleString('nl-NL')} kcal`}
function saveNutrition(){if(!client())return;const meals=Object.fromEntries(MEALS.map(([id])=>[id,$(`#meal-${id}`).value.trim()]));state.nutrition[state.clientId]={carbs:Math.max(0,+$('#carbs').value||0),protein:Math.max(0,+$('#protein').value||0),fat:Math.max(0,+$('#fat').value||0),note:$('#note').value.trim(),meals};persist();toast('Voedingsplan opgeslagen voor '+client().name)}
function schedule(){return state.schedules[state.clientId]||structuredClone(BASE_SCHEDULE)}
function renderPlanning(){if(!client())return noClient();const plan=schedule();return `<div class="intro"><div><span class="label">Weekplanning</span><h2>Planning voor ${esc(client().name)}</h2><p>Deze onderdelen verschijnen per dag in de klantenapp.</p></div></div><section class="card"><div class="schedule">${plan.map((day,i)=>`<div class="schedule-row"><b>${DAYS[i]}</b><select id="type-${i}">${['Training','Rust','Herstel','Conditie'].map(x=>`<option ${x===day.type?'selected':''}>${x}</option>`).join('')}</select><input id="title-${i}" value="${esc(day.title)}"><input id="note-${i}" value="${esc(day.note)}"></div>`).join('')}</div><div class="actions"><button onclick="savePlanning()">Weekplanning opslaan</button></div></section>`}
function savePlanning(){state.schedules[state.clientId]=DAYS.map((day,i)=>({day,type:$(`#type-${i}`).value,title:$(`#title-${i}`).value.trim(),note:$(`#note-${i}`).value.trim()}));persist();toast('Planning opgeslagen voor '+client().name)}
function goals(){return state.goals[state.clientId]||[]}
function renderGoals(){if(!client())return noClient();const list=goals();return `<div class="intro"><div><span class="label">Weekdoelen</span><h2>Doelen voor ${esc(client().name)}</h2><p>Stel concrete doelen in die boven de weekplanning verschijnen.</p></div></div><section class="card"><h3>Nieuw doel</h3><div class="goal-form"><select id="goalPreset" onchange="applyGoalPreset(this.value)"><option value="sleep">8 uur slaap</option><option value="training">4 trainingen per week</option><option value="steps">10.000 stappen per dag</option><option value="water">2 liter water per dag</option><option value="custom">Eigen doel</option></select><input id="goalTitle" value="Gemiddeld 8 uur slapen"><input id="goalTarget" type="number" step="0.5" value="8"><input id="goalUnit" value="uur"><input id="goalPeriod" value="per nacht"><button onclick="addGoal()">Toevoegen</button></div></section><section class="card"><h3>Actieve doelen</h3><div class="goal-list">${list.length?list.map(g=>`<article><div><b>${esc(g.title)}</b><span>${g.target} ${esc(g.unit)} · ${esc(g.period)}</span></div><button onclick="removeGoal('${g.id}')">×</button></article>`).join(''):'<p class="empty">Nog geen doelen ingesteld.</p>'}</div></section>`}
function applyGoalPreset(value){const presets={sleep:['Gemiddeld 8 uur slapen',8,'uur','per nacht'],training:['4 trainingen afronden',4,'trainingen','deze week'],steps:['10.000 stappen per dag',7,'dagen','deze week'],water:['2 liter water per dag',7,'dagen','deze week'],custom:['Eigen doel',1,'keer','deze week']},p=presets[value]||presets.custom;$('#goalTitle').value=p[0];$('#goalTarget').value=p[1];$('#goalUnit').value=p[2];$('#goalPeriod').value=p[3]}
function addGoal(){const title=$('#goalTitle').value.trim(),target=Math.max(.5,+$('#goalTarget').value||0),unit=$('#goalUnit').value.trim(),period=$('#goalPeriod').value.trim();if(!title||!unit)return toast('Vul het doel volledig in');state.goals[state.clientId]=[...goals(),{id:`goal-${Date.now()}`,type:$('#goalPreset').value,title,target,unit,period,current:0}];persist();render();toast('Doel toegevoegd')}
function removeGoal(id){state.goals[state.clientId]=goals().filter(g=>g.id!==id);persist();render();toast('Doel verwijderd')}
function editingPlan(){return state.plans.find(x=>x.id===state.editingPlanId)||state.plans[0]||null}
function renderTraining(){if(!client())return noClient();const plan=editingPlan();if(!plan)return `<section class="empty-state"><h2>Nog geen trainingsschema’s</h2><button onclick="createPlan()">Eerste schema maken</button></section>`;return `<div class="intro"><div><span class="label">Trainingsschema</span><h2>Schema’s beheren</h2><p>Maak schema’s met normale sets, supersets en clustersets en wijs ze aan klanten toe.</p></div><button class="new-plan" onclick="createPlan()">＋ Nieuw schema</button></div><section class="card plan-picker"><label>Bewerk schema<select onchange="selectPlan(this.value)">${state.plans.map(p=>`<option value="${p.id}" ${p.id===plan.id?'selected':''}>${esc(p.title)}</option>`).join('')}</select></label><div class="field"><label>Naam schema</label><input id="planTitle" value="${esc(plan.title)}"></div><div class="field"><label>Omschrijving</label><input id="planDescription" value="${esc(plan.description)}"></div></section><div class="sessions">${plan.sessions.map((session,si)=>`<section class="card session"><div class="session-head"><select id="sessionDay-${si}">${DAYS.map(day=>`<option ${day===session.day?'selected':''}>${day}</option>`).join('')}</select><input id="sessionTitle-${si}" value="${esc(session.title)}"></div><div>${session.exercises.map((exercise,ei)=>exerciseRow(si,ei,exercise)).join('')}</div><button class="add" onclick="addExercise(${si})">＋ Oefening toevoegen</button></section>`).join('')}</div><button class="add session-add" onclick="addSession()">＋ Trainingsdag toevoegen</button><section class="card"><h3>Toewijzen aan klanten</h3><div class="client-checks">${state.clients.map(c=>`<label><input type="checkbox" data-assign="${c.id}" ${state.assignments[c.id]===plan.id?'checked':''}><span><b>${esc(c.name)}</b><small>${esc(c.email)}</small></span></label>`).join('')}</div></section><div class="actions"><button onclick="saveTraining()">Schema opslaan en toewijzen</button></div>`}
function exerciseRow(si,ei,e){return `<div class="exercise" data-exercise="${si}-${ei}"><input value="${esc(e.name)}" aria-label="Oefening"><input type="number" min="1" value="${e.sets}" aria-label="Sets"><input value="${esc(e.reps)}" aria-label="Herhalingen"><select><option value="normal" ${e.method==='normal'?'selected':''}>Normale sets</option><option value="superset-a" ${e.method==='superset-a'?'selected':''}>Superset A</option><option value="superset-b" ${e.method==='superset-b'?'selected':''}>Superset B</option><option value="cluster" ${e.method==='cluster'?'selected':''}>Cluster 6×6 · 10 sec</option></select><button onclick="removeExercise(${si},${ei})">×</button></div>`}
function collectTraining(){const plan=editingPlan();if(!plan)return null;plan.title=$('#planTitle')?.value.trim()||plan.title;plan.description=$('#planDescription')?.value.trim()||'';plan.sessions=plan.sessions.map((session,si)=>({...session,day:$(`#sessionDay-${si}`)?.value||session.day,title:$(`#sessionTitle-${si}`)?.value.trim()||session.title,exercises:[...document.querySelectorAll(`[data-exercise^="${si}-"]`)].map(row=>{const fields=row.querySelectorAll('input,select');return{name:fields[0].value.trim(),sets:+fields[1].value||3,reps:fields[2].value.trim(),method:fields[3].value}})}));return plan}
function selectPlan(id){collectTraining();state.editingPlanId=id;persist();render()}
function addExercise(si){const plan=collectTraining();plan.sessions[si].exercises.push({name:'Nieuwe oefening',sets:3,reps:'10',method:'normal'});render()}
function removeExercise(si,ei){const plan=collectTraining();plan.sessions[si].exercises.splice(ei,1);render()}
function addSession(){const plan=collectTraining();plan.sessions.push({day:'Maandag',title:`Training ${plan.sessions.length+1}`,exercises:[]});render()}
function createPlan(){const plan={...structuredClone(DEFAULT_PLAN),id:`plan-${Date.now()}`,title:'Nieuw trainingsschema'};state.plans.push(plan);state.editingPlanId=plan.id;persist();render()}
function saveTraining(){const plan=collectTraining();if(!plan)return;document.querySelectorAll('[data-assign]').forEach(cb=>{const id=cb.dataset.assign;if(cb.checked)state.assignments[id]=plan.id;else if(state.assignments[id]===plan.id)delete state.assignments[id]});persist();toast('Trainingsschema opgeslagen en toegewezen')}
function syncClientSelect(){const select=$('#clientSelect');if(!select)return;select.innerHTML=state.clients.length?state.clients.map(c=>`<option value="${c.id}" ${c.id===state.clientId?'selected':''}>${esc(c.name)} · ${esc(c.email)}</option>`).join(''):'<option value="">Nog geen klanten</option>';select.disabled=!state.clients.length}
function render(){const titles={clients:'Klanten',nutrition:'Voedingsplan',planning:'Weekplanning',goals:'Doelen',training:'Trainingsschema’s'};$('#title').textContent=titles[state.view]||'Coachportaal';$('#view').innerHTML=state.view==='clients'?renderClients():state.view==='nutrition'?renderNutrition():state.view==='planning'?renderPlanning():state.view==='goals'?renderGoals():renderTraining();document.querySelectorAll('nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view))}
function init(){syncClientSelect();$('#clientSelect').onchange=()=>{state.clientId=$('#clientSelect').value;persist();render()};document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;store.set('coachView',state.view);render()});render()}
init();
