const store={get:(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},set:(key,value)=>localStorage.setItem(key,JSON.stringify(value))};
const CLIENTS=[{id:'sophie',name:'Sophie de Vries',goal:'Sterker worden'},{id:'daan',name:'Daan Jansen',goal:'Vetverlies'},{id:'mila',name:'Mila Bakker',goal:'Conditie opbouwen'}];
const DAYS=['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'];
const MEALS=[['breakfast','Ontbijt'],['snack1','Snack 1'],['lunch','Lunch'],['snack2','Snack 2'],['dinner','Avondeten'],['snack3','Snack 3']];
const BASE_SCHEDULE=[{type:'Training',title:'Full body kracht',note:'60 minuten'},{type:'Rust',title:'Rustdag',note:'Herstel'},{type:'Training',title:'Upper body',note:'50 minuten'},{type:'Herstel',title:'Mobiliteit',note:'20 minuten'},{type:'Training',title:'Full body kracht',note:'60 minuten'},{type:'Conditie',title:'Zone 2 cardio',note:'35 minuten'},{type:'Rust',title:'Rustdag',note:'Herstel'}];
const DEFAULT_PLAN={id:'performance-basis',title:'Performance Basis',description:'Persoonlijk krachtplan.',sessions:[{day:'Maandag',title:'Lower body strength',exercises:[{name:'Back squat',sets:4,reps:'6',method:'normal'}]},{day:'Woensdag',title:'Upper body strength',exercises:[{name:'Bench press',sets:4,reps:'6',method:'cluster'}]}]};
let state={view:'nutrition',clientId:store.get('coachClientId','sophie'),nutrition:store.get('coachNutritionPlans',{}),schedules:store.get('coachSchedules',{}),goals:store.get('coachGoals',{}),plans:store.get('trainingPlans',[DEFAULT_PLAN]),assignments:store.get('clientPlanAssignments',{})};
const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function client(){return CLIENTS.find(x=>x.id===state.clientId)||CLIENTS[0]}
function nutritionPlan(){return state.nutrition[state.clientId]||{carbs:300,protein:150,fat:80,note:'Verdeel je voeding over zes eetmomenten.',meals:{}}}
function renderNutrition(){const p=nutritionPlan(),kcal=p.carbs*4+p.protein*4+p.fat*9;return `<div class="intro"><div><span class="label">Voedingscoaching</span><h2>Voedingsplan voor ${esc(client().name)}</h2><p>Stel de dagelijkse macro's en instructies per eetmoment in. De klant kan deze doelen alleen bekijken.</p></div><span class="pill">Coach bepaalt</span></div><section class="card"><span class="label">Dagdoel</span><h3>Macro's per dag</h3><div class="macro-grid"><div class="field"><label>Koolhydraten (g)</label><input id="carbs" type="number" value="${p.carbs}" oninput="updateKcal()"><small>4 kcal per gram</small></div><div class="field"><label>Eiwit (g)</label><input id="protein" type="number" value="${p.protein}" oninput="updateKcal()"><small>4 kcal per gram</small></div><div class="field"><label>Vet (g)</label><input id="fat" type="number" value="${p.fat}" oninput="updateKcal()"><small>9 kcal per gram</small></div><div class="kcal-preview" id="kcal">${kcal.toLocaleString('nl-NL')} kcal</div></div><div class="field" style="margin-top:12px"><label>Algemene instructie voor de klant</label><textarea id="note" rows="3">${esc(p.note||'')}</textarea></div></section><section class="card"><span class="label">Eetmomenten</span><h3>Richtlijn per maaltijd</h3><div class="meal-guidance">${MEALS.map(([id,label])=>`<div><label>${label}</label><input id="meal-${id}" value="${esc(p.meals?.[id]||'')}" placeholder="Bijv. eiwitrijk en 60 g koolhydraten"></div>`).join('')}</div><div class="actions"><button onclick="saveNutrition()">Voedingsplan opslaan</button></div></section>`}
function updateKcal(){const c=+$(`#carbs`).value||0,p=+$(`#protein`).value||0,f=+$(`#fat`).value||0;$('#kcal').textContent=`${Math.round(c*4+p*4+f*9).toLocaleString('nl-NL')} kcal`}
function saveNutrition(){const meals=Object.fromEntries(MEALS.map(([id])=>[id,$(`#meal-${id}`).value.trim()]));state.nutrition[state.clientId]={carbs:Math.max(0,+$('#carbs').value||0),protein:Math.max(0,+$('#protein').value||0),fat:Math.max(0,+$('#fat').value||0),note:$('#note').value.trim(),meals};store.set('coachNutritionPlans',state.nutrition);toast('Voedingsplan opgeslagen voor '+client().name)}
function schedule(){return state.schedules[state.clientId]||BASE_SCHEDULE}
function renderPlanning(){const plan=schedule();return `<div class="intro"><div><span class="label">Weekplanning</span><h2>Planning voor ${esc(client().name)}</h2><p>Deze onderdelen verschijnen per dag in de klantenapp.</p></div></div><section class="card"><div class="schedule">${plan.map((day,i)=>`<div class="schedule-row"><b>${DAYS[i]}</b><select id="type-${i}">${['Training','Rust','Herstel','Conditie'].map(x=>`<option ${x===day.type?'selected':''}>${x}</option>`).join('')}</select><input id="title-${i}" value="${esc(day.title)}"><input id="note-${i}" value="${esc(day.note)}"></div>`).join('')}</div><div class="actions"><button onclick="savePlanning()">Weekplanning opslaan</button></div></section>`}
function savePlanning(){state.schedules[state.clientId]=DAYS.map((_,i)=>({type:$(`#type-${i}`).value,title:$(`#title-${i}`).value.trim(),note:$(`#note-${i}`).value.trim()}));store.set('coachSchedules',state.schedules);toast('Planning opgeslagen voor '+client().name)}
function goals(){return state.goals[state.clientId]||[]}
function renderGoals(){const list=goals();return `<div class="intro"><div><span class="label">Weekdoelen</span><h2>Doelen voor ${esc(client().name)}</h2><p>Stel concrete doelen in die boven de weekplanning van de klant verschijnen.</p></div></div><section class="card"><h3>Nieuw doel</h3><div class="goal-form"><select id="goalPreset" onchange="applyGoalPreset(this.value)"><option value="sleep">8 uur slaap</option><option value="training">4 trainingen per week</option><option value="steps">10.000 stappen per dag</option><option value="water">2 liter water per dag</option><option value="custom">Eigen doel</option></select><input id="goalTitle" value="Gemiddeld 8 uur slapen" placeholder="Naam doel"><input id="goalTarget" type="number" step="0.5" value="8" placeholder="Doel"><input id="goalUnit" value="uur" placeholder="Eenheid"><input id="goalPeriod" value="per nacht" placeholder="Periode"><button onclick="addGoal()">Toevoegen</button></div></section><section class="card"><h3>Actieve doelen</h3><div class="goal-list">${list.length?list.map(g=>`<article><div><b>${esc(g.title)}</b><span>${g.target} ${esc(g.unit)} · ${esc(g.period||'deze week')}</span></div><button onclick="removeGoal('${g.id}')" aria-label="Verwijder doel">×</button></article>`).join(''):'<p class="empty">Nog geen doelen ingesteld.</p>'}</div></section>`}
function applyGoalPreset(value){const presets={sleep:['Gemiddeld 8 uur slapen',8,'uur','per nacht'],training:['4 trainingen afronden',4,'trainingen','deze week'],steps:['10.000 stappen per dag',7,'dagen','deze week'],water:['2 liter water per dag',7,'dagen','deze week'],custom:['Eigen doel',1,'keer','deze week']},p=presets[value]||presets.custom;$('#goalTitle').value=p[0];$('#goalTarget').value=p[1];$('#goalUnit').value=p[2];$('#goalPeriod').value=p[3]}
function addGoal(){const title=$('#goalTitle').value.trim(),target=Math.max(.5,+$('#goalTarget').value||0),unit=$('#goalUnit').value.trim(),period=$('#goalPeriod').value.trim();if(!title||!unit||!target)return toast('Vul het doel volledig in');state.goals[state.clientId]=[...goals(),{id:`goal-${Date.now()}`,type:$('#goalPreset').value,title,target,unit,period,current:0}];store.set('coachGoals',state.goals);render();toast('Doel toegevoegd voor '+client().name)}
function removeGoal(id){state.goals[state.clientId]=goals().filter(g=>g.id!==id);store.set('coachGoals',state.goals);render();toast('Doel verwijderd')}
function assignedPlan(){const id=state.assignments[state.clientId],plan=state.plans.find(x=>x.id===id);return plan||state.plans[0]||DEFAULT_PLAN}
function renderTraining(){const plan=assignedPlan();return `<div class="intro"><div><span class="label">Trainingsschema</span><h2>Schema voor ${esc(client().name)}</h2><p>Maak oefeningen, supersets en clustersets en wijs het schema aan één of meerdere klanten toe.</p></div><button class="new-plan" onclick="createPlan()">＋ Nieuw schema</button></div><section class="card"><div class="field"><label>Naam schema</label><input id="planTitle" value="${esc(plan.title)}"></div><div class="field" style="margin-top:8px"><label>Omschrijving</label><input id="planDescription" value="${esc(plan.description)}"></div></section><div class="sessions">${plan.sessions.map((session,si)=>`<section class="card session"><div class="session-head"><select id="sessionDay-${si}">${DAYS.map(day=>`<option ${day===session.day?'selected':''}>${day}</option>`).join('')}</select><input id="sessionTitle-${si}" value="${esc(session.title)}"></div><div id="exercises-${si}">${session.exercises.map((exercise,ei)=>exerciseRow(si,ei,exercise)).join('')}</div><button class="add" onclick="addExercise(${si})">＋ Oefening toevoegen</button></section>`).join('')}</div><section class="card"><h3>Toewijzen aan klanten</h3><div class="client-checks">${CLIENTS.map(c=>`<label><input type="checkbox" data-assign="${c.id}" ${state.assignments[c.id]===plan.id?'checked':''}><span><b>${esc(c.name)}</b><small>${esc(c.goal)}</small></span></label>`).join('')}</div></section><div class="actions"><button onclick="saveTraining()">Schema opslaan en toewijzen</button></div>`}
function exerciseRow(si,ei,e){return `<div class="exercise" data-exercise="${si}-${ei}"><input value="${esc(e.name)}" aria-label="Oefening"><input type="number" value="${e.sets}" aria-label="Sets"><input value="${esc(e.reps)}" aria-label="Herhalingen"><select><option value="normal" ${e.method==='normal'?'selected':''}>Normale sets</option><option value="superset-a" ${e.method==='superset-a'?'selected':''}>Superset A</option><option value="superset-b" ${e.method==='superset-b'?'selected':''}>Superset B</option><option value="cluster" ${e.method==='cluster'?'selected':''}>Cluster 6×6 · 10 sec</option></select><button onclick="removeExercise(${si},${ei})">×</button></div>`}
function collectTraining(){const plan=assignedPlan();plan.title=$('#planTitle').value.trim();plan.description=$('#planDescription').value.trim();plan.sessions=plan.sessions.map((session,si)=>({...session,day:$(`#sessionDay-${si}`).value,title:$(`#sessionTitle-${si}`).value.trim(),exercises:[...document.querySelectorAll(`[data-exercise^="${si}-"]`)].map(row=>{const fields=row.querySelectorAll('input,select');return{name:fields[0].value,sets:+fields[1].value||3,reps:fields[2].value,method:fields[3].value}})}));return plan}
function addExercise(si){const plan=collectTraining();plan.sessions[si].exercises.push({name:'Nieuwe oefening',sets:3,reps:'10',method:'normal'});render()}
function removeExercise(si,ei){const plan=collectTraining();plan.sessions[si].exercises.splice(ei,1);render()}
function createPlan(){const plan={id:`plan-${Date.now()}`,title:'Nieuw trainingsschema',description:'Persoonlijk schema.',sessions:[{day:'Maandag',title:'Training 1',exercises:[{name:'Nieuwe oefening',sets:3,reps:'10',method:'normal'}]}]};state.plans.push(plan);state.assignments[state.clientId]=plan.id;render()}
function saveTraining(){const plan=collectTraining();if(!state.plans.some(x=>x.id===plan.id))state.plans.push(plan);document.querySelectorAll('[data-assign]').forEach(cb=>{const id=cb.dataset.assign;if(cb.checked)state.assignments[id]=plan.id;else if(state.assignments[id]===plan.id)delete state.assignments[id]});store.set('trainingPlans',state.plans);store.set('clientPlanAssignments',state.assignments);toast('Trainingsschema opgeslagen en toegewezen')}
function render(){const titles={nutrition:'Voedingsplan',planning:'Weekplanning',goals:'Doelen',training:'Trainingsschema’s'};$('#title').textContent=titles[state.view];$('#view').innerHTML=state.view==='nutrition'?renderNutrition():state.view==='planning'?renderPlanning():state.view==='goals'?renderGoals():renderTraining();document.querySelectorAll('nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view))}
function init(){const select=$('#clientSelect');select.innerHTML=CLIENTS.map(c=>`<option value="${c.id}" ${c.id===state.clientId?'selected':''}>${esc(c.name)} · ${esc(c.goal)}</option>`).join('');select.onchange=()=>{state.clientId=select.value;store.set('coachClientId',state.clientId);render()};document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;render()});render()}
init();
